version: '3.8'
services:
  mariadb:
    image: mariadb:10.4.12
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - centos_test_network
  centos_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./php/81/php.ini:/etc/php.ini
      - ./php/81/www.conf:/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log/php-fpm
      - ./home/bitrix/b2b-forms.ingkacentres.com/public_html:/home/bitrix/b2b-forms.ingkacentres.com/public_html
    restart: always
    # command: tail -f /dev/null
    container_name: ${APP_NAME}_php
    networks:
      - centos_test_network
  nginx_service:
    image: nginx:latest
    container_name: ${APP_NAME}_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
      - ./home/bitrix/b2b-forms.ingkacentres.com/public_html:/home/bitrix/b2b-forms.ingkacentres.com/public_html
    restart: always
    ports:
      - "3781:80"
    depends_on:
      - centos_service 
    networks:
      - centos_test_network
volumes:
  mariadb_data:
    driver: local
networks:
    centos_test_network:
      name: ${APP_NAME}_network
      driver: bridge