version: '3.8'
services:
  mariadb:
    image: mariadb:10.4.12
    container_name: ${APP_NAME}_mariadb
    env_file:
      - .env
    volumes:
      - ./mariadb_data:/var/lib/mysql
    # ports:
    #   - "3436:3306"
    networks:
      - centos_test_network
  centos_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    env_file:
      - .env
    volumes:
      - ./home/bitrix/b2b-forms.ingkacentres.com/public_html:/home/bitrix/b2b-forms.ingkacentres.com/public_html
      - ./home/bitrix/tmp:/bitrix/tmp
    restart: always
    # command: tail -f /dev/null
    container_name: ${APP_NAME}_php
    # user: "${UID}:${GID}"
    depends_on:
      - mariadb
    networks:
      - centos_test_network
  centos_service_83:
    build:
      context: .
      dockerfile: php83.Dockerfile
    env_file:
      - .env
    volumes:
      - ./php/83/php.ini:/etc/php.ini
      - ./php/83/www.conf:/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log/php-fpm
      - ./home/bitrix/b2b-forms.ingkacentres.com/public_html:/home/bitrix/b2b-forms.ingkacentres.com/public_html
      - ./home/bitrix/tmp:/home/bitrix/tmp
    restart: always
    # command: tail -f /dev/null
    container_name: ${APP_NAME}_83php
    depends_on:
      - mariadb
    networks:
      - centos_test_network
  nginx_service:
    image: nginx:latest
    container_name: ${APP_NAME}_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
      - ./home/bitrix/b2b-forms.ingkacentres.com/public_html:/home/bitrix/b2b-forms.ingkacentres.com/public_html
      - ./home/bitrix/tmp:/home/bitrix/tmp
    restart: always
    ports:
      - "3781:80"
    depends_on:
      - centos_service 
    networks:
      - centos_test_network
volumes:
  mariadb_data:
    driver: local
networks:
    centos_test_network:
      name: b2b-form-container_network
      driver: bridge
